---
title: "task2-biomarkers"
author: "Nursima Çalık"
date: "2026-09-23"
output: html_document
---
## Upload Data
```{r}
measurements <- read.csv("data/measurements.csv")
metadata <- read.csv("data/metadata.csv")
```

## Examine data

```{r}
dim(measurements)
str(measurements)
head(measurements)
anyNA(measurements)

dim(metadata)
str(metadata)
head(metadata)
table(metadata$group)
table(metadata$sex)
anyNA(metadata)
```

## Merge data files 
 
```{r}
library(dplyr)
base::nrow(measurements)
base::nrow(metadata)

base::names(measurements)
base::names(metadata)

base::length(base::unique(measurements$sample_id))
base::length(base::unique(metadata$sample_id))

combination_data <- dplyr::left_join(x=measurements, y=metadata, by = "sample_id")
```

## Examine combination data

```{r}
dim(combination_data)
str(combination_data)
head(combination_data)
anyNA(combination_data)
duplicated(combination_data$sample_id)
sum(duplicated(combination_data$sample_id))
```

## Explore data results
How are the biomarker measurements distributed?
```{r}
library(ggplot2)
ggplot(data = combination_data, aes(x=biomarker_ng_ml, y=sample_id)) +
  geom_point(size=1)+
  labs(title= "Distribution of Biomarker Measurements", x ="biomarker(ng/ml)", y="Samples") +
  theme_minimal()

mean(combination_data$biomarker_ng_ml, na.rm = TRUE)
sd(combination_data$biomarker_ng_ml, na.rm = TRUE)
max(combination_data$biomarker_ng_ml)
min(combination_data$biomarker_ng_ml)

```
Does the treatment group appear different from the control group?
```{r}
ggplot(data=combination_data, aes(x = group, y=biomarker_ng_ml)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(
    width = 0.08,
    height = 0
  ) +
  labs(title = "Difference Between Control and Treatment Group", x = "Sex", y = "Biomarker(ng/ml)") +
  theme_minimal()

library(dplyr)
Control <-filter(combination_data, group == "Control")
mean(Control$biomarker_ng_ml, na.rm = TRUE)
Treatment <-filter(combination_data, group == "Treatment")
mean(Treatment$biomarker_ng_ml, na.rm = TRUE)
sd(Control$biomarker_ng_ml, na.rm = TRUE)
sd(Treatment$biomarker_ng_ml, na.rm = TRUE)

```
Does age appear to be associated with the biomarker?
```{r}
ggplot(data = combination_data, aes(x = age, y = biomarker_ng_ml , group = group)) +
  geom_point(size = 1, aes(color = group)) +
  scale_y_continuous(breaks = seq(8, 20, by = 1)) +
  scale_x_continuous(breaks = seq(25, 70,by = 2)) +
  labs(title = "Relationship with Age", x = "Age", y= "Biomarker(ng/ml)" )+
  theme_minimal()
```
Does sex appear to be associated with the biomarker?
```{r}
ggplot(data = Control, aes(x=sex, y= biomarker_ng_ml))+
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(
    width = 0.08,
    height = 0
  )+
  labs(title = "Relationship with Sex at Control Group",x = "Sex", y ="Biomarker(ng/ml)")+
  theme_minimal()

ggplot(data = Treatment, aes(x=sex, y= biomarker_ng_ml))+
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(
    width = 0.08,
    height = 0
  )+
  labs(title = "Relationship with Sex at Treatment Group",x = "Sex", y ="Biomarker(ng/ml)")+
  theme_minimal()

aggregate(biomarker_ng_ml ~ sex, data = Control, FUN = mean)
aggregate(biomarker_ng_ml ~ sex, data = Treatment, FUN = mean)
aggregate(biomarker_ng_ml ~ sex, data = Control, FUN = sd)
aggregate(biomarker_ng_ml ~ sex, data = Treatment, FUN = sd)

```
Do the measurement batches appear different?
```{r}
sum(combination_data$batch == "B1")
sum(combination_data$batch == "B2")

B1 <-filter(combination_data, batch == "B1")
B2 <-filter(combination_data, batch == "B2")

ggplot(data= B1, aes(x= group, y= biomarker_ng_ml))+
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(
    width = 0.08,
    height = 0
  )+
  labs(title = "Difference Between Groups in B1", X= "Group", y= "Biomarker(ng/ml)")+
  theme_minimal()

ggplot(data= B2, aes(x= group, y= biomarker_ng_ml))+
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(
    width = 0.08,
    height = 0
  )+
  labs(title = "Difference Between Groups in B2 ", X= "Group", y= "Biomarker(ng/ml)")+
  theme_minimal()

aggregate(biomarker_ng_ml ~ group, data = B1, FUN = mean )
aggregate(biomarker_ng_ml ~ group, data = B2, FUN = mean )
aggregate(biomarker_ng_ml ~ group, data = B1, FUN = sd )
aggregate(biomarker_ng_ml ~ group, data = B2, FUN = sd )
```






